init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test:
  assemblies:
    - TKV.Tests.dll
os: Visual Studio 2015
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
